using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Threading;
using AnoMech.Helpers;
using AnoMech.Pointers;
using Dalamud.Game.Addon.Lifecycle;
using Dalamud.Game.Addon.Lifecycle.AddonArgTypes;
using Dalamud.Game.ClientState.Conditions;
using Dalamud.Hooking;
using FFXIVClientStructs.FFXIV.Client.Game;
using FFXIVClientStructs.FFXIV.Client.Game.Character;
using FFXIVClientStructs.FFXIV.Client.Game.Event;
using FFXIVClientStructs.FFXIV.Client.Game.UI;
using FFXIVClientStructs.FFXIV.Client.Graphics.Environment;
using FFXIVClientStructs.FFXIV.Client.Network;
using FFXIVClientStructs.FFXIV.Client.UI.Agent;
using Lumina.Excel.Sheets;
using static FFXIVClientStructs.FFXIV.Client.Network.PacketDispatcher.Delegates;

namespace AnoMech.Core.Map;

// Client-side zone loading and packet firewall. Ported from Hyperborea (Memory.cs
// + Utils.cs). Must be in the Inn before calling Enter(); Leave() reloads the inn.
// All public methods must be called from the framework thread.
public sealed unsafe class ZoneSession : IDisposable
{
    private class SessionSave
    {
        public uint TerritoryId { get; set; }
        public Vector3 Position { get; set; }
        public float Rotation { get; set; }
        public int Exp { get; set; }
        public uint RestedExp { get; set; }
        public bool LevelSync { get; set; }
        public int Level { get; set; }
        public bool ItemLevelSync { get; set; }
        public Dictionary<int, int> Attributes { get; } = new();
    }

    // TerritoryIntendedUse.Inn = 2 (from ECommons TerritoryIntendedUseEnum)
    private const uint InnIntendedUse = 2;

    // ── Native delegates ──────────────────────────────────────────────────────

    private delegate byte SendPacketDelegate(nint a1, nint a2, nint a3, byte a4);
    private readonly Hook<SendPacketDelegate> sendPacketHook;

    // OnReceivePacket delegate type generated by FFXIVClientStructs from [VirtualFunction(1)]
    private readonly Hook<OnReceivePacket> receivePacketHook;

    // ── State ─────────────────────────────────────────────────────────────────

    private readonly ushort heartbeatOpcode;
    private uint? loadedInstanceContent;

    // ── 防火牆自檢用的觀測狀態（B-001）──────────────────────────────────
    //
    // 兩個 hook 從 plugin 載入起就常駐啟用，但分兩種模式：
    //   Passive  — 只計數，一律呼叫 Original（＝完全不改變遊戲行為）
    //   Blocking — 真正的防火牆（送出只放行心跳；接收只放行 allowlist）
    //
    // 為什麼要有 Passive：防火牆最危險的失效是「hook 沒掛上」或「掃到錯的函式」，
    // 這兩種情況下畫面全正常、build 全綠、沒有任何警告，但封包會照送給伺服器。
    // 常駐 Passive 讓我們在**進入模擬區之前**就能觀察到「detour 確實會被呼叫」
    // 以及「心跳 opcode 判定正確」——看到心跳通過一次，這兩件事同時被證明。
    // 這樣自檢不必等待、也不必為了檢查而阻斷任何封包。
    // volatile：由 framework thread 寫入、由封包 detour 讀取（不保證同一條 thread），
    // 沒有 volatile 的話 JIT 可以把讀取提到迴圈外或快取住舊值——
    // 那會讓「已切到 Blocking」與「detour 仍在放行」出現時間差，正是不能接受的。
    private volatile bool blocking;

    private long sendSeenTotal;       // detour 被呼叫的總次數（證明 hook 活著）
    private long sendSeenHeartbeat;   // 其中判定為心跳的次數（證明 opcode 對）
    private long recvSeenTotal;

    // 絆線：Blocking 期間，心跳以外的封包絕不該走到 Original。
    // 這在程式邏輯上不可能發生；一旦非 0 代表有人改壞了 detour，屬立即中止的訊號。
    private long blockedLeakCount;

    internal long SendSeenTotal => Interlocked.Read(ref sendSeenTotal);
    internal long SendSeenHeartbeat => Interlocked.Read(ref sendSeenHeartbeat);
    internal long RecvSeenTotal => Interlocked.Read(ref recvSeenTotal);
    internal long BlockedLeakCount => Interlocked.Read(ref blockedLeakCount);
    internal ushort HeartbeatOpcode => heartbeatOpcode;
    internal bool SendHookLive => sendPacketHook is { IsDisposed: false, IsEnabled: true };
    internal bool RecvHookLive => receivePacketHook is { IsDisposed: false, IsEnabled: true };
    internal nint SendHookAddress => sendPacketHook?.Address ?? 0;
    internal nint RecvHookAddress => receivePacketHook?.Address ?? 0;

    // Set true right before we open the Social window for a party resync; the Social
    // PostSetup listener closes it again and clears this. Distinguishes our open from
    // a manual one so manual opens aren't auto-closed.
    private bool autoCloseSocial;

    private readonly ZoneRestoration restoration;
    public bool IsActive => restoration.IsActive;
    public bool IsRestoring => restoration.IsRestoring;
    internal bool HasRestoreFailed => restoration.HasFailed;
    internal OpcodeAllowlist IncomingOpcodes { get; } = new();
    private bool disposed;
    private long zoneGeneration;
    private Func<bool>? networkRunGuard;
    private Func<bool>? restoreCompletionGuard;

    internal void SetRestoreCompletionGuard(Func<bool> guard) => restoreCompletionGuard = guard;

    internal void SetNetworkRunGuard(Func<bool>? guard) => networkRunGuard = guard;

    private readonly SessionSave sessionSave = new();

    private void ReportRestorationFailure(Exception error)
    {
        const string instruction = "[AnoMech] 場地恢復失敗，已維持安全隔離。"
            + "請輸入 /anomech leave 重試；若仍失敗，請重新啟動遊戲，勿熱重新載入插件。";
        CrashTrace.Log($"{instruction} {error}");
        var generation = zoneGeneration;
        try
        {
            // Queue failures can be reported by a background Task observer.
            _ = Plugin.Framework.Run(() =>
            {
                if (!disposed && generation == zoneGeneration && restoration.HasFailed)
                    ChatOutput.Error(instruction, required: true);
            }).ContinueWith(
                task => CrashTrace.Log($"[ZoneSession] Recovery notification failed: {task.Exception}"),
                System.Threading.CancellationToken.None,
                System.Threading.Tasks.TaskContinuationOptions.OnlyOnFaulted |
                System.Threading.Tasks.TaskContinuationOptions.ExecuteSynchronously,
                System.Threading.Tasks.TaskScheduler.Default);
        }
        catch (Exception dispatchError)
        {
            CrashTrace.Log($"[ZoneSession] Recovery notification could not be queued: {dispatchError}");
        }
    }

    // ── Construction ──────────────────────────────────────────────────────────

    public ZoneSession()
    {
        restoration = new ZoneRestoration(
            RestoreSavedZone,
            CompleteRestoration,
            completion => Plugin.Framework.RunOnTick(completion, TimeSpan.FromSeconds(1)),
            ReportRestorationFailure);

        // Heartbeat (ZoneUp) opcode — auto-detected by signature (from Hyperborea Memory.cs)
        heartbeatOpcode = (ushort)Marshal.ReadInt32(
            Plugin.SigScanner.ScanText("C7 44 24 ?? ?? ?? ?? ?? 48 F7 F1") + 0x4);
        CrashTrace.Log($"[ZoneSession] Heartbeat opcode: {heartbeatOpcode}");

        // Send-packet hook (sig from Hyperborea Memory.cs)
        var sendAddr = Plugin.SigScanner.ScanText(
            "48 89 5C 24 ?? 48 89 74 24 ?? 4C 89 64 24 ?? 55 41 56 41 57 48 8B EC 48 83 EC 70");
        sendPacketHook = Plugin.GameInterop.HookFromAddress<SendPacketDelegate>(
            sendAddr, SendPacketDetour);

        // Receive-packet hook — address from PacketDispatcher.StaticVirtualTablePointer->OnReceivePacket.
        // This is the standard approach used by ECommons/Dalamud's GameNetwork service.
        // PacketDispatcher.Delegates.OnReceivePacket and StaticVirtualTablePointer are generated by
        // FFXIVClientStructs from [VirtualFunction(1)] + [VirtualTable] on PacketDispatcher.
        var receiveAddr = (nint)PacketDispatcher.StaticVirtualTablePointer->OnReceivePacket;
        CrashTrace.Log($"[ZoneSession] OnReceivePacket: {receiveAddr:X}");
        receivePacketHook = Plugin.GameInterop.HookFromAddress<OnReceivePacket>(
            receiveAddr, ReceivePacketDetour);

        Plugin.AddonLifecycle.RegisterListener(AddonEvent.PostSetup, "Social", OnSocialPostSetup);

        // 兩個 hook 從這裡起常駐啟用，但以 Passive 模式運作（只計數、一律放行）。
        // 這讓 FirewallSelfCheck 能在進入模擬區之前就證明 hook 真的活著、
        // 且心跳 opcode 判定正確——見上方 blocking 欄位的註解。
        // Passive 對遊戲沒有行為影響：每個封包只多一次 opcode 比對與計數。
        sendPacketHook.Enable();
        receivePacketHook.Enable();

        CrashTrace.Log("[ZoneSession] Initialized（hook 常駐，模式＝Passive）。");
    }

    // ── Public API ────────────────────────────────────────────────────────────

    /// <summary>
    /// 可以起始模擬的私人區域。
    ///
    /// 上游只允許旅館（TerritoryIntendedUse=2），但那是**挑的不變量、不是技術限制**：
    /// 真正需要的性質是「私人、非戰鬥、不會有一堆真人在場」。台服 client 實資料
    /// （tc_TerritoryType.csv）中符合的還有房屋內部與公寓。
    ///
    /// 刻意**不含** IntendedUse=13（住宅區戶外）——那裡有其他玩家。
    ///
    /// ⚠️ 房屋內部的已知代價：回程走 client-side 重載，而家具是伺服器串流的
    /// EventObject ⇒ 回到房屋後家具可能不見，要真的換一次區才會重新拿到。
    /// 旅館幾乎沒有這類物件，這就是上游選旅館的原因。
    /// </summary>
    private static readonly uint[] PrivateStartIntendedUses =
    {
        InnIntendedUse,   //  2 旅館（8 個，上游原本的唯一選項）
        14,               // 14 房屋內部：小屋／公館／宅邸（38 個，個人與部隊共用地圖）
        49,               // 49 公寓房間（1 個）
    };

    public static bool IsInInn()
    {
        var row = Plugin.DataManager.GetExcelSheet<TerritoryType>()
            ?.GetRowOrDefault(Plugin.ClientState.TerritoryType);
        if (row == null) return false;
        return Array.IndexOf(PrivateStartIntendedUses, row.Value.TerritoryIntendedUse.RowId) >= 0;
    }

    // Any state in which the local player can't freely act. Used as a second
    // gate before starting a scenario from an inn so we don't kick off mid-
    // cutscene, mid-NPC-event, mid-craft, mid-zone, etc.
    public static bool IsPlayerBusy()
    {
        var c = Plugin.Condition;
        return c[ConditionFlag.WatchingCutscene]
            || c[ConditionFlag.WatchingCutscene78]
            || c[ConditionFlag.OccupiedInCutSceneEvent]
            || c[ConditionFlag.OccupiedInEvent]
            || c[ConditionFlag.OccupiedInQuestEvent]
            || c[ConditionFlag.OccupiedSummoningBell]
            || c[ConditionFlag.Occupied30]
            || c[ConditionFlag.Occupied33]
            || c[ConditionFlag.Occupied38]
            || c[ConditionFlag.Occupied39]
            || c[ConditionFlag.Crafting]
            || c[ConditionFlag.ExecutingCraftingAction]
            || c[ConditionFlag.PreparingToCraft]
            || c[ConditionFlag.Gathering]
            || c[ConditionFlag.ExecutingGatheringAction]
            || c[ConditionFlag.Fishing]
            || c[ConditionFlag.TradeOpen]
            || c[ConditionFlag.BetweenAreas]
            || c[ConditionFlag.LoggingOut]
            || c[ConditionFlag.WaitingForDutyFinder]
            || c[ConditionFlag.InDutyQueue]
            || c[ConditionFlag.InCombat]
            || c[ConditionFlag.Mounted]
            || c[ConditionFlag.Jumping]
            || c[ConditionFlag.Occupied];
    }

    // Load the target territory, teleport player to playerSpawn, enable firewall.
    // Firewall is enabled before the zone load (matching Hyperborea's sequence).
    public void Enter(uint territoryId, Vector3 playerSpawn, byte levelSync, ushort itemLevelSync, uint layerFilterKey = 0)
    {
        ContentFinderCondition? cfc = null;
        try
        {
            restoration.Enter(
                () =>
                {
                    var localPlayer = Plugin.ObjectTable.LocalPlayer;
                    var gm = GameMain.Instance();
                    if (localPlayer == null || localPlayer.Address == 0 || gm == null ||
                        EventFramework.Instance() == null || Conditions.Instance() == null ||
                        (itemLevelSync != 0 && UIState.Instance() == null))
                        throw new InvalidOperationException("Zone entry requires the local player and native singletons.");
                    cfc = GetContentFinderCondition(territoryId)
                        ?? throw new InvalidOperationException($"Territory {territoryId} has no content finder condition.");
                    var position = localPlayer.Position;
                    var rotation = localPlayer.Rotation;
                    var savedTerritory = gm->CurrentTerritoryTypeId;
                    if (!ZoneRestoration.MatchesPose(savedTerritory, savedTerritory,
                            position, position, rotation, rotation))
                        throw new InvalidOperationException("The original territory or player pose cannot be restored.");

                    sessionSave.TerritoryId = savedTerritory;
                    sessionSave.Position = position;
                    sessionSave.Rotation = rotation;
                    sessionSave.Exp = Plugin.PlayerState.GetClassJobExperience(Plugin.PlayerState.ClassJob.Value);
                    sessionSave.RestedExp = Plugin.PlayerState.BaseRestedExperience;
                    sessionSave.LevelSync = levelSync != 0;
                    sessionSave.Level = localPlayer.Level;
                    sessionSave.ItemLevelSync = itemLevelSync != 0;
                    sessionSave.Attributes.Clear();
                },
                () =>
                {
                    ++zoneGeneration;
                    EnableFirewall();
                    LoadZoneInternal(territoryId, false, playerSpawn,
                        layerFilterKey: layerFilterKey, contentFinderCondition: cfc);
                    CrashTrace.Log($"[ZoneSession] Entered territory {territoryId}.");
                });
        }
        catch
        {
            // 前置失敗不凍結玩家；native變更開始後的失敗仍由同一離場流程恢復。
            if (restoration.HasFailed)
            {
                var condition = Conditions.Instance();
                if (condition != null) condition->Occupied = true;
            }
            throw;
        }
    }

    // Immediately set the active weather. Must be called on the framework thread.
    // weatherId is a Weather-sheet row; transition is the fade time in seconds.
    public void SetWeather(byte weatherId, float transition = 0.5f)
    {
        var env = EnvManager.Instance();
        if (env == null) return;
        env->ActiveWeather = weatherId;
        env->TransitionTime = transition;
    }

    // Apply weather after a fresh zone load. Delayed 1 second so the engine finishes setup.
    //
    // RunOnTick rather than Task.Delay(...).ContinueWith(... Framework.Run ...): the latter keeps
    // the timer on the thread pool, so an unload during the delay window leaves the continuation
    // to fire against a torn-down framework (or never fire at all). RunOnTick owns both the delay
    // and the thread affinity and is cancelled with the framework. Same shape for the two delayed
    // tasks in Revert below — all three were the ContinueWith form before 2026-08-23.
    public void ApplyWeather(byte weatherId)
    {
        var generation = zoneGeneration;
        var guard = networkRunGuard;
        Plugin.Framework.RunOnTick(() =>
        {
            if (!disposed && generation == zoneGeneration && guard?.Invoke() != false)
                SetWeather(weatherId);
        }, TimeSpan.FromSeconds(1));
    }

    // 正常離場只在延遲驗證成功後交還控制；失敗保留資料及隔離供明示重試。
    // Dispose維持既有同步停用策略，不能冒稱卸載後仍有防火牆或安全熱reload。
    public void Revert(bool dispose)
    {
        if (!dispose)
        {
            restoration.Revert();
            return;
        }

        var needsRestore = restoration.IsActive;
        restoration.Dispose();
        ++zoneGeneration;
        if (!needsRestore) return;

        // 卸載時不能等待framework callback；這是舊停用契約，不供正常Leave使用。
        try
        {
            if (sessionSave.TerritoryId != 0)
                LoadZoneInternal(sessionSave.TerritoryId, true, sessionSave.Position, sessionSave.Rotation);
        }
        catch (Exception ex)
        {
            CrashTrace.Log($"[ZoneSession] Revert(dispose) LoadZoneInternal failed: {ex}");
        }
        try
        {
            SetLocalPlayerPosition(sessionSave.Position, sessionSave.Rotation);
        }
        catch (Exception ex)
        {
            CrashTrace.Log($"[ZoneSession] Revert(dispose) cleanup failed: {ex}");
        }
        finally
        {
            var condition = Conditions.Instance();
            if (condition != null) condition->Occupied = false;
            else CrashTrace.Log("[ZoneSession] Conditions.Instance() was null; Occupied not cleared.");
            DisableFirewall();
            sessionSave.TerritoryId = 0;
        }
        Plugin.Framework.Run(OpenSocialForPartyResync);
    }

    private void RestoreSavedZone()
    {
        ++zoneGeneration; // 使舊天候／Social callback失效，不清除復原資料。
        if (sessionSave.TerritoryId == 0)
            throw new InvalidOperationException("No original territory is available for restoration.");
        var condition = Conditions.Instance();
        if (condition == null)
            throw new InvalidOperationException("Conditions is unavailable during zone restoration.");
        condition->Occupied = true;
        LoadZoneInternal(sessionSave.TerritoryId, true, sessionSave.Position, sessionSave.Rotation);
    }

    private void CompleteRestoration()
    {
        if (restoreCompletionGuard?.Invoke() == false)
            throw new InvalidOperationException("Simulation cleanup is incomplete; zone isolation must remain enabled.");
        // 仍在framework thread，且已保留原本1秒延遲；不能在失敗的finally放行。
        SetLocalPlayerPosition(sessionSave.Position, sessionSave.Rotation);
        var localPlayer = Plugin.ObjectTable.LocalPlayer;
        var gm = GameMain.Instance();
        if (localPlayer == null || localPlayer.Address == 0 || gm == null ||
            !ZoneRestoration.MatchesPose(gm->CurrentTerritoryTypeId, sessionSave.TerritoryId,
                localPlayer.Position, sessionSave.Position, localPlayer.Rotation, sessionSave.Rotation))
            throw new InvalidOperationException("Original native territory/player pose has not been restored "
                + "(position tolerance=0.01, rotation tolerance=0.001 rad).");
        if (sessionSave.LevelSync && localPlayer.Level != sessionSave.Level)
            throw new InvalidOperationException("Original player level has not been restored.");
        if (sessionSave.ItemLevelSync && sessionSave.Attributes.Count != 0)
        {
            var uiState = UIState.Instance();
            if (uiState == null)
                throw new InvalidOperationException("UIState is unavailable while verifying restored attributes.");
            foreach (var (baseParamId, value) in sessionSave.Attributes)
                if (uiState->PlayerState.Attributes[baseParamId] != value)
                    throw new InvalidOperationException($"Original attribute {baseParamId} has not been restored.");
        }
        var condition = Conditions.Instance();
        if (condition == null)
            throw new InvalidOperationException("Conditions is unavailable at restoration completion.");
        condition->Occupied = false;
        DisableFirewall();
        sessionSave.TerritoryId = 0;
        sessionSave.Attributes.Clear();
        CrashTrace.Log("[ZoneSession] Original territory, player pose and sync restored.");

        // 原Social回覆會更新MainGroup／HUD；成功恢復後才排這個非必要操作。
        var generation = zoneGeneration;
        try
        {
            Plugin.Framework.RunOnTick(() =>
            {
                if (!disposed && generation == zoneGeneration && !IsActive)
                    OpenSocialForPartyResync();
            }, TimeSpan.FromMilliseconds(500));
        }
        catch (Exception ex)
        {
            CrashTrace.Log($"[ZoneSession] Party HUD resync scheduling failed after restoration: {ex}");
        }
    }

    // Opens the Social agent, which issues its own (callback-routed) party-member
    // request and processes the reply into the party HUD — the step a bare RequestData
    // can't trigger. Firing this from the settled inn state mirrors a manual open.
    private void OpenSocialForPartyResync()
    {
        var am = AgentModule.Instance();
        var social = am != null ? am->GetAgentByInternalId(AgentId.Social) : null;
        if (social == null) return;
        autoCloseSocial = true;
        social->Show();
        CrashTrace.Log("[ZoneSession] Opened Social for party resync.");
    }

    // Closes the Social window again as soon as it finishes opening — but only when
    // we opened it (autoCloseSocial), so a manual open is left alone.
    private void OnSocialPostSetup(AddonEvent type, AddonArgs args)
    {
        if (!autoCloseSocial) return;
        autoCloseSocial = false;

        var am = AgentModule.Instance();
        var s = am != null ? am->GetAgentByInternalId(AgentId.Social) : null;
        if (s != null) s->Hide();
        CrashTrace.Log("[ZoneSession] Auto-closed Social after party resync.");
    }

    // hook 本身常駐（見建構函式），這裡只切換 Passive ↔ Blocking。
    // 刻意不再 Enable/Disable hook：hook 的安裝與拆卸是有風險的操作，
    // 而且「已安裝」正是自檢要驗證的前提，反覆拆裝會讓自檢結果失效。
    public void EnableFirewall()
    {
        blocking = true;
        CrashTrace.Log("[ZoneSession] 防火牆模式 → Blocking");
    }

    public void DisableFirewall()
    {
        blocking = false;
        CrashTrace.Log("[ZoneSession] 防火牆模式 → Passive");
    }

    // ── Zone loading sequence (mirrors Hyperborea Utils.LoadZone) ─────────────

    private void LoadZoneInternal(uint territory, bool unloading, Vector3 playerPos, float? rotation = null,
        uint layerFilterKey = 0, ContentFinderCondition? contentFinderCondition = null)
    {
        var eventFramework = EventFramework.Instance();
        var gm = GameMain.Instance();
        CrashTrace.Log($"[ZoneSession] LoadZone territory={territory} ef={((nint)eventFramework):X} gm={((nint)gm):X}");
        if (eventFramework == null || gm == null)
        {
            throw new InvalidOperationException("Native zone-loading singletons are unavailable.");
        }

        var localPlayer = Plugin.ObjectTable.LocalPlayer;
        if (localPlayer == null || localPlayer.Address == 0)
            throw new InvalidOperationException("The local player is unavailable during zone loading.");
        var player = (Character*)localPlayer.Address;

        var classJobId = (byte)Plugin.PlayerState.ClassJob.RowId;

        CrashTrace.Log("[ZoneSession] Step 1: FinalizeInstanceContent");
        if (unloading || loadedInstanceContent != null)
        {
            var uiState = UIState.Instance();
            ZoneRestoration.RestoreInstanceState(ref loadedInstanceContent,
                contentId =>
                {
                    if (uiState != null) uiState->DirectorTodo.IsShown = false;
                    EventFrameworkPointers.TerminateDirector(eventFramework, 0x80030000 + contentId);
                },
                () => ResetSync(uiState, player, classJobId));
        }

        CrashTrace.Log("[ZoneSession] Step 2: DisableDraw all objects");
        foreach (var obj in Plugin.ObjectTable)
        {
            if (obj.Address == IntPtr.Zero) continue;
            ((FFXIVClientStructs.FFXIV.Client.Game.Object.GameObject*)obj.Address)->DisableDraw();
        }

        if (!unloading)
        {
            CrashTrace.Log("[ZoneSession] Step 3: InitDirector");

            var cfc = contentFinderCondition
                ?? throw new InvalidOperationException("Zone entry requires a prevalidated content finder condition.");

            var contentId = cfc.Content.RowId;
            CrashTrace.Log($"[ZoneSession] ContentId={contentId}");

            EventFrameworkPointers.InitDirector(eventFramework, 0x80030000 + contentId, contentId, 0);

            loadedInstanceContent = contentId;
            InstanceContentDirectorHelper.SetDutyData(cfc);

            SetSync(cfc, player, territory, classJobId);
        }
        else
        {
            CrashTrace.Log("[ZoneSession] Step 3: InitDirector (Skipped)");
        }

        CrashTrace.Log($"[ZoneSession] Step 4: LoadZone (native) layerFilterKey={layerFilterKey}");
        GameMainPointers.LoadZone(gm, territory, layerFilterKey, 0, 1);

        CrashTrace.Log("[ZoneSession] Step 5: SetupTerritoryType");
        eventFramework->SetTerritoryTypeId((ushort)territory);

        CrashTrace.Log("[ZoneSession] Step 6: SyncClientState");
        SyncClientStateTerritoryType((ushort)territory);

        CrashTrace.Log("[ZoneSession] Step 7: SetPosition");
        SetLocalPlayerPosition(playerPos, rotation);

        CrashTrace.Log("[ZoneSession] LoadZone complete");
    }

    private void SetLocalPlayerPosition(Vector3 position, float? rotation = null)
    {
        if (Plugin.ObjectTable.LocalPlayer is { Address: var addr } && addr != IntPtr.Zero)
        {
            var chara = (Character*)addr;
            chara->GameObject.SetPosition(position.X, position.Y, position.Z);

            if (rotation != null)
            {
                chara->GameObject.SetRotation(rotation.Value);
            }
        }
        else
        {
            throw new InvalidOperationException("The local player is unavailable for position restoration.");
        }
    }

    private ContentFinderCondition? GetContentFinderCondition(uint territoryId)
    {
        var sheet = Plugin.DataManager.GetExcelSheet<TerritoryType>();

        if (sheet == null)
        {
            Plugin.Log.Debug($"[ZoneSession.GetContentFinderCondition] TerritoryType sheet was null.");
            return null;
        }

        var rowRef = sheet[territoryId].ContentFinderCondition;

        if (!rowRef.IsValid)
        {
            Plugin.Log.Debug($"TerritoryType sheet, index {territoryId} does not have a valid ContentFinderCondition reference.");
            return null;
        }

        return rowRef.Value;
    }

    private static void SyncClientStateTerritoryType(ushort territory)
    {
        try
        {
            var type = Plugin.ClientState.GetType();
            var prop = type.GetProperty("TerritoryType",
                BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);
            if (prop?.CanWrite == true)
            {
                prop.SetValue(Plugin.ClientState, territory);
                return;
            }
            var field = type.GetField("territoryType",
                BindingFlags.NonPublic | BindingFlags.Instance)
                ?? type.GetField("TerritoryType",
                BindingFlags.NonPublic | BindingFlags.Instance);
            field?.SetValue(Plugin.ClientState, territory);
        }
        catch (Exception e)
        {
            Plugin.Log.Warning($"[ZoneSession] Could not sync ClientState.TerritoryType: {e.Message}");
        }
    }

    // (Item) Level Sync
    private void SetSync(ContentFinderCondition cfc, Character* player, uint territory, byte classJobId)
    {
        var cfcLevelSync = cfc.ClassJobLevelSync;
        CrashTrace.Log($"[同步] LevelSync={sessionSave.LevelSync}（cfc 同步等級 {cfcLevelSync}，現等 {Plugin.PlayerState.Level}）"
                     + $" ItemLevelSync={sessionSave.ItemLevelSync}（cfc iLv {cfc.ItemLevelSync}/{cfc.ItemLevelRequired}）");

        if (sessionSave.LevelSync)
        {
            var currentLevel = (byte)Plugin.PlayerState.Level;
            var levelSynced = currentLevel > cfcLevelSync;
            CrashTrace.Log($"[同步] 等級 {currentLevel} → {(levelSynced ? cfcLevelSync : currentLevel)}");

            if (levelSynced)
            {
                if (player != null)
                {
                    player->Level = cfcLevelSync;
                }

                var updateClassInfoPacket = new UpdateClassInfoPacket
                {
                    ClassJobId = classJobId,
                    CurrentLevel = currentLevel,
                    ClassJobLevel = currentLevel,
                    SyncedLevel = cfcLevelSync,
                    ClassJobExp = 0,
                    BaseRestedExperience = 0
                };

                PacketDispatcherPointers.HandleUpdateClassInfoPacket(0, &updateClassInfoPacket);
            }
        }

        if (sessionSave.ItemLevelSync)
        {
            var uiState = UIState.Instance();
            if (uiState != null)
            {
                var ilvlSync = cfc.ItemLevelSync != 0 ? cfc.ItemLevelSync : cfc.ItemLevelRequired;

                if (ilvlSync != 0)
                {
                    Plugin.Log.Debug($"Setting up iLvl sync to {ilvlSync}");
                    var syncedAttributes = GetSyncedAttributes(cfcLevelSync, ilvlSync);

                    foreach (var (baseParamId, value) in syncedAttributes)
                    {
                        sessionSave.Attributes[baseParamId] = uiState->PlayerState.Attributes[baseParamId];
                        uiState->PlayerState.Attributes[baseParamId] = value;
                    }
                }
            }
        }
    }

    private void ResetSync(UIState* uiState, Character* player, byte classJobId)
    {
        if (player == null || (sessionSave.ItemLevelSync && sessionSave.Attributes.Count != 0 && uiState == null))
            throw new InvalidOperationException("Native state required to restore player sync is unavailable.");

        if (sessionSave.LevelSync)
        {
            var updateClassInfoPacket = new UpdateClassInfoPacket
            {
                ClassJobId = classJobId,
                CurrentLevel = (ushort)sessionSave.Level,
                ClassJobLevel = (ushort)sessionSave.Level,
                SyncedLevel = 0,
                ClassJobExp = (ushort)sessionSave.Exp,
                BaseRestedExperience = sessionSave.RestedExp
            };

            PacketDispatcherPointers.HandleUpdateClassInfoPacket(0, &updateClassInfoPacket);

            if (player != null)
            {
                player->Level = (byte)sessionSave.Level;
            }
        }

        if (sessionSave.ItemLevelSync && uiState != null)
        {
            foreach (var (baseParamId, value) in sessionSave.Attributes)
            {
                uiState->PlayerState.Attributes[baseParamId] = value;
            }
        }
    }

    private Dictionary<int, int> GetSyncedAttributes(byte level, ushort ilvl)
    {
        var stats = new Dictionary<int, int>();

        var itemSheet = Plugin.DataManager.GetExcelSheet<Item>();
        var baseParamSheet = Plugin.DataManager.GetExcelSheet<BaseParam>();
        var paramGrowSheet = Plugin.DataManager.GetExcelSheet<ParamGrow>();

        var supportedAttributes = new PlayerAttribute[]
        {
                PlayerAttribute.SkillSpeed,
                PlayerAttribute.SpellSpeed
        };

        foreach (var attribute in supportedAttributes)
        {
            switch (attribute)
            {
                case PlayerAttribute.SkillSpeed:
                case PlayerAttribute.SpellSpeed:
                    stats[(int)attribute] = paramGrowSheet[level].BaseSpeed;
                    break;
                default:
                    continue;
            }
        }

        // Get Item Stats
        var inventoryManager = InventoryManager.Instance();
        var equippedItems = inventoryManager->GetInventoryContainer(InventoryType.EquippedItems);

        for (int i = 0; i < equippedItems->GetSize(); i++)
        {
            var inventoryItem = equippedItems->Items[i];
            var itemId = inventoryItem.ItemId;

            if (itemId == 0)
            {
                continue;
            }

            var item = itemSheet[itemId];
            var itemLevel = item.LevelItem.RowId;
            
            if (item.LevelItem.RowId <= ilvl) // Add it as is if the ilvl is the same or less than sync
            {
                Plugin.Log.Debug($"Item \"{item.Name}\" (ilvl {item.LevelItem.RowId}) fits the ilvl sync requirements.");

                for (int x = 0; x < item.BaseParam.Count; x++)
                {
                    var baseParam = item.BaseParam[x];
                    var baseParamId = (int)baseParam.RowId;

                    if (!supportedAttributes.Contains((PlayerAttribute)baseParamId))
                    {
                        continue;
                    }

                    stats[baseParamId] += item.BaseParamValue[x];
                }

                // Add extra stats
                ApplyExtraStats(stats, GetMateriaStats(inventoryItem));
                ApplyExtraStats(stats, GetMandervilleWeaponStats(inventoryItem));
            }
            else // Calculate the sync value
            {
                var resistanceStats = new Dictionary<int, int>();

                var resistanceSheet = Plugin.DataManager.GetExcelSheet<ResistanceWeaponAdjust>();
                if (resistanceSheet.TryGetRow(itemId, out var _))
                {
                    resistanceStats = GetMateriaStats(inventoryItem);
                }

                var mandervilleStats = GetMandervilleWeaponStats(inventoryItem);

                // Doing this instead of calling ExdModule.GetItemRowById because it's not guaranteed to always return on this frame
                var dummyItem = new byte[0xA0];
                fixed (byte* dummyItemPtr = dummyItem)
                {
                    *(dummyItemPtr + 0x54) = item.BaseParamModifier;
                    *(ushort*)(dummyItemPtr + 0x8A) = ilvl;
                    *(dummyItemPtr + 0x9A) = (byte)item.EquipSlotCategory.RowId;

                    for (int x = 0; x < item.BaseParam.Count; x++)
                    {
                        var baseParam = item.BaseParam[x];
                        var baseParamId = (int)baseParam.RowId;

                        if (!supportedAttributes.Contains((PlayerAttribute)baseParamId))
                        {
                            continue;
                        }

                        var statValue = item.BaseParamValue[x];

                        if (resistanceStats.TryGetValue(baseParamId, out var resistanceStat))
                        {
                            statValue += (short)resistanceStat;
                        }

                        if (mandervilleStats.TryGetValue(baseParamId, out var mandervilleStat))
                        {
                            statValue += (short)mandervilleStat;
                        }

                        var statMaxValue = (int)InventoryItem.GetParameterMaxValue((uint)baseParamId, dummyItemPtr);
                        var syncedValue = int.Min(statValue, statMaxValue);
                        stats[baseParamId] += syncedValue;

                        Plugin.Log.Debug($"Item \"{item.Name}\" (ilvl {item.LevelItem.RowId})'s {(PlayerAttribute)baseParamId} was synced to {syncedValue}");
                    }
                }
            }
        }

        // Get Food Buffs
        var localPlayer = (BattleChara*)Plugin.ObjectTable.LocalPlayer!.Address;

        if (localPlayer != null)
        {
            var statusManager = localPlayer->StatusManager;

            foreach (var status in statusManager.Status)
            {
                var statusId = status.StatusId;

                if (statusId == 0 || statusId != 48)
                {
                    continue;
                }
                
                var hq = status.Param > 10000;
                var foodId = hq ? status.Param - 10000 : status.Param;

                if (!Plugin.DataManager.GetExcelSheet<ItemFood>().TryGetRow((uint)foodId, out var food))
                {
                    continue;
                }
                
                foreach (var bonus in food.Params)
                {
                    var stat = (int)bonus.BaseParam.RowId;
                    
                    if (stat == 0 || !stats.ContainsKey(stat))
                    {
                        continue;
                    }

                    var value = hq ? bonus.ValueHQ : bonus.Value;
                    var max = hq ? bonus.MaxHQ : bonus.Max;
                    int statBuff;

                    if (bonus.IsRelative)
                    {
                        var currentStat = stats[stat];
                        var percentBuff = (int)(currentStat * (value / 100f));
                        statBuff = int.Min(percentBuff, max);
                    }
                    else
                    {
                        statBuff = value;
                    }

                    stats[stat] += statBuff;
                }
            }
        }

        return stats;
    }

    // This also works for Resistance Weapons
    private Dictionary<int, int> GetMateriaStats(InventoryItem inventoryItem)
    {
        var stats = new Dictionary<int, int>();
        var materiaSheet = Plugin.DataManager.GetExcelSheet<Materia>();

        for (int i = 0; i < inventoryItem.Materia.Length; i++)
        {
            var materiaId = inventoryItem.Materia[i];

            if (materiaId == 0 || !materiaSheet.TryGetRow(materiaId, out var materiaRow))
            {
                continue;
            }

            var index = inventoryItem.MateriaGrades[i];
            var statValue = materiaRow.Value[index];
            var stat = materiaRow.BaseParam.RowId;
            stats[(int)stat] = statValue;
        }

        return stats;
    }

    // https://github.com/VioletStardustXIV/XivGearExport/blob/main/XivGearExport/XivGearSet.cs#L447
    private Dictionary<int, int> GetMandervilleWeaponStats(InventoryItem inventoryItem)
    {
        var stats = new Dictionary<int, int>();

        var statsSheet = Plugin.DataManager.GetExcelSheet<MandervilleWeaponEnhance>();
        var materiaSheet = Plugin.DataManager.GetExcelSheet<Materia>();

        if (!statsSheet.TryGetRow(inventoryItem.ItemId, out var _))
        {
            return stats;
        }

        for (int i = 0; i < inventoryItem.Materia.Length; i++)
        {
            var materiaId = inventoryItem.Materia[i];

            if (materiaId == 0 || !materiaSheet.TryGetRow(materiaId, out var materiaRow))
            {
                continue;
            }

            var index = inventoryItem.MateriaGrades[i];
            var statValue = materiaRow.Value[index];

            switch (materiaId)
            {
                case 1403:
                    stats[(int)PlayerAttribute.CriticalHit] = statValue;
                    break;
                case 1404:
                    stats[(int)PlayerAttribute.DirectHitRate] = statValue;
                    break;
                case 1405:
                    stats[(int)PlayerAttribute.Determination] = statValue;
                    break;
                case 1406:
                    stats[(int)PlayerAttribute.SkillSpeed] = statValue;
                    break;
                case 1407:
                    stats[(int)PlayerAttribute.SpellSpeed] = statValue;
                    break;
                case 1408:
                    stats[(int)PlayerAttribute.Tenacity] = statValue;
                    break;
                case 1409:
                    stats[(int)PlayerAttribute.Piety] = statValue;
                    break;
            }
        }

        return stats;
    }

    private void ApplyExtraStats(Dictionary<int, int> stats, Dictionary<int, int> extraStats)
    {
        foreach (var (attribute, value) in extraStats)
        {
            if (!stats.ContainsKey(attribute))
            {
                continue;
            }

            stats[attribute] += value;
        }
    }

    // ── Packet firewall detours (mirrored from Hyperborea Memory.cs) ──────────

    // 送出側呼叫 Original 的**唯一出口**，並在此重驗一次不變式。
    //
    // 目前呼叫端的條件已保證不會違反，所以這個 guard 在今天是不會觸發的。
    // 它存在的理由不是「處理可能的錯誤」，而是把「什麼情況下封包才准出去」
    // 收斂成一個看得到的守衛：日後若有人在別處加了第二條 Original 路徑、
    // 或把條件改壞，會在這裡被計數而不是靜默外洩。
    // 這是紅線 1 的防護，代價是一次布林比較。
    private byte SendOriginalGuarded(nint a1, nint a2, nint a3, byte a4, bool isHeartbeat)
    {
        if (blocking && !isHeartbeat)
        {
            Interlocked.Increment(ref blockedLeakCount);
            Plugin.Log.Error(
                "[ZoneSession] 不變式違反：Blocking 期間有非心跳封包試圖送出，已攔下。"
                + "這代表 detour 的判斷邏輯被改壞了——請勿在此狀態下繼續使用。");
            return 1;
        }
        return sendPacketHook.Original(a1, a2, a3, a4);
    }

    private byte SendPacketDetour(nint a1, nint a2, nint a3, byte a4)
    {
        const byte defaultReturn = 1;
        if (a2 == IntPtr.Zero) return defaultReturn;
        try
        {
            Interlocked.Increment(ref sendSeenTotal);
            var isHeartbeat = *(ushort*)a2 == heartbeatOpcode;
            if (isHeartbeat) Interlocked.Increment(ref sendSeenHeartbeat);

            // Passive：完全不改變遊戲行為。
            // Blocking：只有心跳出得去，其餘吞掉並假裝送出成功。
            if (!blocking || isHeartbeat)
                return SendOriginalGuarded(a1, a2, a3, a4, isHeartbeat);
        }
        catch (Exception e)
        {
            // 例外時走 fail-closed：回傳 defaultReturn 而不呼叫 Original。
            // 寧可斷線，也不能在假副本狀態下把封包漏給伺服器。
            Plugin.Log.Error($"[ZoneSession] SendPacketDetour: {e.Message}");
            return defaultReturn;
        }
        return defaultReturn;
    }

    private void ReceivePacketDetour(PacketDispatcher* a1, uint a2, nint a3)
    {
        if (a3 == IntPtr.Zero) return;
        try
        {
            Interlocked.Increment(ref recvSeenTotal);

            // Passive：一律放行。
            if (!blocking) { receivePacketHook.Original(a1, a2, a3); return; }

            // Release builds and User builds always run the firewall (safe mode hardcoded on).
            // Debug 建置尊重設定開關，可以關掉
            // for testing without affecting shipped behaviour.
            const bool safeMode = true;
            if (!safeMode || IncomingOpcodes.Contains(*(ushort*)(a3 + 2)))
                receivePacketHook.Original(a1, a2, a3);
        }
        catch (Exception e)
        {
            Plugin.Log.Error($"[ZoneSession] ReceivePacketDetour: {e.Message}");
        }
    }

    // ── Lifecycle ─────────────────────────────────────────────────────────────

    public void Dispose()
    {
        Plugin.AddonLifecycle.UnregisterListener(AddonEvent.PostSetup, "Social", OnSocialPostSetup);

        // To not freeze a player that's disabling/reloading/etc the plugin while not in a Scenario
        //
        // 健檢 2026-09-05 M15：Revert(true) 炸掉時也必須繼續往下拆 hook——detour 沒拆
        // 就卸載插件，下次載入會重打一次（舊 detour 還掛在原生函式上）。
        try
        {
            if (IsActive || IsRestoring)
            {
                Revert(true);
            }
            else
            {
                DisableFirewall(); // 切回 Passive
            }
        }
        catch (Exception ex)
        {
            CrashTrace.Log($"[ZoneSession] Dispose revert failed: {ex}");
        }
        restoration.Dispose();
        disposed = true;
        ++zoneGeneration;
        networkRunGuard = null;

        // hook 現在是常駐的（見建構函式），Dispose 才是真正拆下來的地方。
        sendPacketHook.Disable();
        receivePacketHook.Disable();
        sendPacketHook.Dispose();
        receivePacketHook.Dispose();
    }
}
